<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalManagementSystem" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-DENT5RFJ;Initial Catalog=HospitalManagementSystem;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="HospitalManagementSystem.Properties.Settings" SettingsPropertyName="HospitalManagementSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.doctor" Member="doctors">
    <Type Name="doctor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="doctor_category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="city_of_birth" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="assigned_room" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="doctor_meeting" Member="meetings" ThisKey="id" OtherKey="doctor_id" Type="meeting" />
      <Association Name="doctor_category_doctor" Member="doctor_category" ThisKey="doctor_category_id" OtherKey="id" Type="doctor_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.doctor_category" Member="doctor_categories">
    <Type Name="doctor_category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="doctor_category_doctor" Member="doctors" ThisKey="id" OtherKey="doctor_category_id" Type="doctor" />
      <Association Name="doctor_category_icd_11_doctor_recommendation" Member="icd_11_doctor_recommendations" ThisKey="id" OtherKey="doctor_category_id" Type="icd_11_doctor_recommendation" />
    </Type>
  </Table>
  <Table Name="dbo.[icd-11]" Member="icd_11s">
    <Type Name="icd_11">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="icd_11_icd_11_doctor_recommendation" Member="icd_11_doctor_recommendations" ThisKey="id" OtherKey="icd_11_id" Type="icd_11_doctor_recommendation" />
      <Association Name="icd_11_icd_11_exclusion" Member="icd_11_exclusions" ThisKey="id" OtherKey="icd_11_id" Type="icd_11_exclusion" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="Char(128) NOT NULL" CanBeNull="false" />
      <Column Name="last_login_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[icd-11_doctor_recommendation]" Member="icd_11_doctor_recommendations">
    <Type Name="icd_11_doctor_recommendation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[icd-11_id]" Member="icd_11_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="doctor_category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="doctor_category_icd_11_doctor_recommendation" Member="doctor_category" ThisKey="doctor_category_id" OtherKey="id" Type="doctor_category" IsForeignKey="true" />
      <Association Name="icd_11_icd_11_doctor_recommendation" Member="icd_11" ThisKey="icd_11_id" OtherKey="id" Type="icd_11" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[icd-11_exclusion]" Member="icd_11_exclusions">
    <Type Name="icd_11_exclusion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[icd-11_id]" Member="icd_11_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="exclusion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="icd_11_icd_11_exclusion" Member="icd_11" ThisKey="icd_11_id" OtherKey="id" Type="icd_11" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.meeting" Member="meetings">
    <Type Name="meeting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="patient_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="doctor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="room" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="queue_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="meeting_patient_record" Member="patient_records" ThisKey="id" OtherKey="meeting_id" Type="patient_record" />
      <Association Name="meeting_payment" Member="payments" ThisKey="id" OtherKey="meeting_id" Type="payment" />
      <Association Name="doctor_meeting" Member="doctor" ThisKey="doctor_id" OtherKey="id" Type="doctor" IsForeignKey="true" />
      <Association Name="patient_meeting" Member="patient" ThisKey="patient_id" OtherKey="id" Type="patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.patient" Member="patients">
    <Type Name="patient">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="city_of_birth" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="blood_type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="patient_meeting" Member="meetings" ThisKey="id" OtherKey="patient_id" Type="meeting" />
      <Association Name="patient_patient_record" Member="patient_records" ThisKey="id" OtherKey="patient_id" Type="patient_record" />
    </Type>
  </Table>
  <Table Name="dbo.patient_record" Member="patient_records">
    <Type Name="patient_record">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="patient_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="meeting_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="meeting_patient_record" Member="meeting" ThisKey="meeting_id" OtherKey="id" Type="meeting" IsForeignKey="true" />
      <Association Name="patient_patient_record" Member="patient" ThisKey="patient_id" OtherKey="id" Type="patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.payment" Member="payments">
    <Type Name="payment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="meeting_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="card_holder_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="primary_account_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="expiration_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="service_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_payment" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="payment_payment_detail" Member="payment_details" ThisKey="id" OtherKey="payment_id" Type="payment_detail" />
      <Association Name="meeting_payment" Member="meeting" ThisKey="meeting_id" OtherKey="id" Type="meeting" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.payment_detail" Member="payment_details">
    <Type Name="payment_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="payment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="nominal" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="payment_payment_detail" Member="payment" ThisKey="payment_id" OtherKey="id" Type="payment" IsForeignKey="true" />
    </Type>
  </Table>
</Database>